---
# tasks file for os6

 - name: "Collect already configured SNMP communities"
   os6_command:
     commands:
       - "show running-config | include \"snmp-server community\""
   when:  ((os6_cfg_deploy | default('True')) | bool)
   register: snmp_communities

 - name: "Generating SNMP configuration for os6"
   template:
      src: os6_snmp.j2
      dest: "{{ build_dir }}/snmp6_{{ hostname }}.conf.part"
   when: ((os6_cfg_generate | default('False')) | bool)
#   notify: save config os6
   register: generate_output

 - name: "Provisioning SNMP configuration for os6"
   dellemc.os6.os6_config:
      src: os6_snmp.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellemc.os6.os6") and ((os6_cfg_deploy | default('True')) | bool)
#   notify: save config os6
   register: output
